main:
  ENABLE: true
perm:
  USE_COMMAND: 'broadcastdonate.use'
settings:
  COLSOLE_ONLY: true
msg:
  MESSAGE: '&2BroadcastDonate &8» &fPlayer &6%player% &fdonated to &6%donate%'
  NO_PERMISSION: '&2BroadcastDonate &8» &fYou have no permission.'
  USAGE: '&2BroadcastDonate &8» &fUsage: &6/bcdonate <player>'